version: '3'

tasks:
  install_python_deps:
    cmds:
      - pip install -r python/requirements.txt

  install_cpp_deps:
    cmds:
      - echo "Installiere C++-Abhängigkeiten (z.B. mit vcpkg oder apt-get)"
      # - vcpkg install <paket> # Beispiel

  install_backend_deps:
    cmds:
      - npm install --prefix backend

  install_all:
    deps: [install_python_deps, install_cpp_deps, install_backend_deps]

  build_cpp:
    cmds:
      - cmake -S cpp -B cpp/build
      - cmake --build cpp/build

  test_cpp:
    cmds:
      - ./cpp/build/myTests

  test_python:
    cmds:
      - python3 python/tests_runner.py

  test_backend:
    cmds:
      - npm test --prefix node

  test_all:
    deps: [test_cpp, test_python, test_backend]

  # ===== Code-Ausführung =====

  run_python:
    cmds:
      - python3 python/main.py

  run_cpp:
    cmds:
      - ./cpp/build/main # Passe den Namen ggf. an, z.B. main, app, etc.

  run_backend:
    cmds:
      - node backend/index.js

  run_all:
    deps: [run_python, run_backend]